const HIRAGANA_RECORDINGS: Record<string, string> = {
  'あ': 'a.mp3',
  'い': 'i.mp3',
  'う': 'u-v3.mp3',
  'え': 'e.mp3',
  'お': 'o.mp3',
  'か': 'ka.mp3',
  'き': 'ki.mp3',
  'く': 'ku.mp3',
  'け': 'ke.mp3',
  'こ': 'ko.mp3',
  'さ': 'sa.mp3',
  'し': 'shi.mp3',
  'す': 'su.mp3',
  'せ': 'se.mp3',
  'そ': 'so.mp3',
  'た': 'ta.mp3',
  'ち': 'chi.mp3',
  'つ': 'tsu.mp3',
  'て': 'te.mp3',
  'と': 'to.mp3',
  'な': 'na.mp3',
  'に': 'ni.mp3',
  'ぬ': 'nu.mp3',
  'ね': 'ne.mp3',
  'の': 'no.mp3',
  'は': 'ha.mp3',
  'ひ': 'hi.mp3',
  'ふ': 'fu.mp3',
  'へ': 'he.mp3',
  'ほ': 'ho.mp3',
  'ま': 'ma.mp3',
  'み': 'mi.mp3',
  'む': 'mu.mp3',
  'め': 'me.mp3',
  'も': 'mo.mp3',
  'や': 'ya.mp3',
  'ゆ': 'yu.mp3',
  'よ': 'yo.mp3',
  'ら': 'ra.mp3',
  'り': 'ri.mp3',
  'る': 'ru.mp3',
  'れ': 're.mp3',
  'ろ': 'ro.mp3',
  'わ': 'wa.mp3',
  'を': 'wo.mp3',
  'ん': 'n.mp3',
  'が': 'ga.mp3',
  'ぎ': 'gi.mp3',
  'ぐ': 'gu.mp3',
  'げ': 'ge.mp3',
  'ご': 'go.mp3',
  'ざ': 'za.mp3',
  'じ': 'ji.mp3',
  'ず': 'zu.mp3',
  'ぜ': 'ze.mp3',
  'ぞ': 'zo.mp3',
  'だ': 'da.mp3',
  'ぢ': 'di.mp3',
  'づ': 'du.mp3',
  'で': 'de.mp3',
  'ど': 'do.mp3',
  'ば': 'ba.mp3',
  'び': 'bi.mp3',
  'ぶ': 'bu.mp3',
  'べ': 'be.mp3',
  'ぼ': 'bo.mp3',
  'ぱ': 'pa.mp3',
  'ぴ': 'pi.mp3',
  'ぷ': 'pu.mp3',
  'ぺ': 'pe.mp3',
  'ぽ': 'po.mp3',
}

const HIRAGANA_WORD_RECORDINGS: Record<string, string> = {
  'あい': 'ai.mp3',
  'いえ': 'ie.mp3',
  'うえ': 'ue.mp3',
  'あお': 'ao.mp3',
  'あう': 'au.mp3',
  'おい': 'oi.mp3',
  'かお': 'kao.mp3',
  'いか': 'ika.mp3',
  'あか': 'aka.mp3',
  'かき': 'kaki.mp3',
  'きく': 'kiku.mp3',
  'こえ': 'koe.mp3',
  'けいこ': 'keiko.mp3',
  'さけ': 'sake.mp3',
  'あさ': 'asa.mp3',
  'くさ': 'kusa.mp3',
  'すし': 'sushi.mp3',
  'せかい': 'sekai.mp3',
  'うそ': 'uso.mp3',
  'たこ': 'tako.mp3',
  'いち': 'ichi.mp3',
  'くつ': 'kutsu.mp3',
  'て': 'te.mp3',
  'とけい': 'tokei.mp3',
  'そと': 'soto.mp3',
  'さかな': 'sakana.mp3',
  'なつ': 'natsu.mp3',
  'いぬ': 'inu.mp3',
  'ねこ': 'neko.mp3',
  'きのう': 'kinou.mp3',
  'はな': 'hana.mp3',
  'はと': 'hato.mp3',
  'ひと': 'hito.mp3',
  'ふね': 'fune.mp3',
  'へた': 'heta.mp3',
  'ほし': 'hoshi.mp3',
  'まつ': 'matsu.mp3',
  'みみ': 'mimi.mp3',
  'むし': 'mushi.mp3',
  'め': 'me.mp3',
  'くも': 'kumo.mp3',
  'もも': 'momo.mp3',
  'へや': 'heya.mp3',
  'やま': 'yama.mp3',
  'ゆき': 'yuki.mp3',
  'ふゆ': 'fuyu.mp3',
  'よむ': 'yomu.mp3',
  'そら': 'sora.mp3',
  'よる': 'yoru.mp3',
  'さくら': 'sakura.mp3',
  'とり': 'tori.mp3',
  'くるま': 'kuruma.mp3',
  'これ': 'kore.mp3',
  'こころ': 'kokoro.mp3',
  'わたし': 'watashi.mp3',
  'かわ': 'kawa.mp3',
  'ほん': 'hon.mp3',
  'かぎ': 'kagi.mp3',
  'えいが': 'eiga.mp3',
  'りんご': 'ringo.mp3',
  'げた': 'geta.mp3',
  'ごま': 'goma.mp3',
  'ぐみ': 'gumi.mp3',
  'かぜ': 'kaze.mp3',
  'ひざ': 'hiza.mp3',
  'じかん': 'jikan.mp3',
  'みず': 'mizu.mp3',
  'ぞう': 'zou.mp3',
  'ざる': 'zaru.mp3',
  'だれ': 'dare.mp3',
  'うで': 'ude.mp3',
  'まど': 'mado.mp3',
  'つづく': 'tsuzuku.mp3',
  'はなぢ': 'hanaji.mp3',
  'ちぢむ': 'chijimu.mp3',
  'ばら': 'bara.mp3',
  'くび': 'kubi.mp3',
  'ぶた': 'buta.mp3',
  'かべ': 'kabe.mp3',
  'ぼうし': 'boushi.mp3',
  'ぱぱ': 'papa.mp3',
  'ぴかぴか': 'pikapika.mp3',
  'ぷにぷに': 'punipuni.mp3',
  'ぺこぺこ': 'pekopeko.mp3',
  'ぽかぽか': 'pokapoka.mp3',
}

const HIRAGANA_ROW_RECORDINGS: Record<string, string> = {
  'あ、い、う、え、お': 'a.mp3',
  'か、き、く、け、こ': 'ka.mp3',
  'さ、し、す、せ、そ': 'sa.mp3',
  'た、ち、つ、て、と': 'ta.mp3',
  'な、に、ぬ、ね、の': 'na.mp3',
  'は、ひ、ふ、へ、ほ': 'ha.mp3',
  'ま、み、む、め、も': 'ma.mp3',
  'や、ゆ、よ': 'ya.mp3',
  'ら、り、る、れ、ろ': 'ra.mp3',
  'わ、を、ん': 'wa.mp3',
  'が、ぎ、ぐ、げ、ご': 'ga.mp3',
  'ざ、じ、ず、ぜ、ぞ': 'za.mp3',
  'だ、ぢ、づ、で、ど': 'da.mp3',
  'ば、び、ぶ、べ、ぼ': 'ba.mp3',
  'ぱ、ぴ、ぷ、ぺ、ぽ': 'pa.mp3',
}

export type BeginnerAudioKind = 'kana' | 'word' | 'row'

/** Returns an approved Beginner Mode recording when one exists. */
export function findBeginnerAudio(text: string, kind: BeginnerAudioKind): string | undefined {
  const normalized = text.trim()
  if (kind === 'kana') {
    const file = HIRAGANA_RECORDINGS[normalized]
    return file ? `${import.meta.env.BASE_URL}audio/beginner/hiragana/${file}` : undefined
  }
  if (kind === 'word') {
    const file = HIRAGANA_WORD_RECORDINGS[normalized]
    return file ? `${import.meta.env.BASE_URL}audio/beginner/hiragana/words/${file}` : undefined
  }
  const file = HIRAGANA_ROW_RECORDINGS[normalized]
  return file ? `${import.meta.env.BASE_URL}audio/beginner/hiragana/rows/${file}` : undefined
}
