import { writeFileSync } from 'node:fs'
import { allCards } from '../src/data'
import { generateSentenceForWord } from '../src/lib/categorySentenceEngine'

/**
 * Precomputes one example sentence per vocabulary word using the shared
 * categorySentenceEngine, so the app can show engine-quality examples without
 * paying the generation cost at render time (deciding a word fits nowhere costs
 * hundreds of milliseconds, and some screens build hundreds of examples in one
 * synchronous pass). Generation is seeded off the word, so re-running this
 * reproduces the same sentences unless the engine's rules or vocabulary change.
 *
 * Re-run with: npm run generate:vocab-examples
 */
const entries: string[] = []
const vocab = allCards.filter((card) => card.type === 'vocab')
const seen = new Set<string>()

for (const card of vocab) {
  if (seen.has(card.front)) continue
  seen.add(card.front)
  const sentence = generateSentenceForWord(card.front)
  if (!sentence) continue
  const segments = sentence.furigana.map((part) => ({ text: part.text, reading: part.reading || part.text }))
  entries.push(`  ${JSON.stringify(card.front)}: ${JSON.stringify({
    japanese: sentence.japanese,
    reading: sentence.reading,
    english: sentence.english,
    segments,
  })},`)
}

const file = `// Generated by scripts/generate-vocab-examples.ts — do not hand-edit.
// Re-run \`npm run generate:vocab-examples\` after changing the sentence
// engine's rules or vocabulary.

export interface GeneratedVocabExample {
  japanese: string
  reading: string
  english: string
  segments: Array<{ text: string; reading: string }>
}

export const GENERATED_VOCAB_EXAMPLES: Record<string, GeneratedVocabExample> = {
${entries.join('\n')}
}
`

writeFileSync('src/data/vocabExamples.generated.ts', file)
console.log(`wrote ${entries.length} example sentences for ${seen.size} unique words`)
