import { readFileSync, writeFileSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'
import { kanjiLabEntries } from '../src/lib/kanjiLabCatalog'

const sourcePath = process.argv[2]
if (!sourcePath) throw new Error('Pass the path to kanjidic2.xml.gz')

const targetCharacters = new Set(kanjiLabEntries.map((entry) => entry.character))
const xml = gunzipSync(readFileSync(sourcePath)).toString('utf8')
const readings: Record<string, { on: string[]; kun: string[] }> = {}

for (const entry of xml.matchAll(/<character>([\s\S]*?)<\/character>/g)) {
  const body = entry[1]
  const character = body.match(/<literal>([^<]+)<\/literal>/)?.[1]
  const grade = Number(body.match(/<grade>(\d+)<\/grade>/)?.[1])
  const isJoyo = grade >= 1 && grade <= 8
  if (!character || (!targetCharacters.has(character) && !isJoyo)) continue

  const on = [...body.matchAll(/<reading r_type="ja_on"[^>]*>([^<]+)<\/reading>/g)]
    .map((match) => match[1]!)
  const kun = [...body.matchAll(/<reading r_type="ja_kun"[^>]*>([^<]+)<\/reading>/g)]
    .map((match) => match[1]!.replace(/\..*$/, '').replace(/^-/, ''))
  readings[character] = { on, kun }
}

const output = `/**\n * Japanese readings derived from the KANJIDIC2 dataset by the Electronic\n * Dictionary Research and Development Group (EDRDG).\n * Source: https://www.edrdg.org/kanjidic/kanjd2index_legacy.html\n * Generated by scripts/generate-kanji-reading-data.ts.\n */\nexport const kanjiReadings: Record<string, { on: string[]; kun: string[] }> = ${JSON.stringify(readings, null, 2)}\n`

writeFileSync('src/data/kanjiReadings.generated.ts', output)
